### ISSUE TITLE
Rename FDSIDList.ICAO to FDSIDList.ICAOCode

### ISSUE THREAD

**Issue by zpopovcic-identyum** [regulaforensics/DocumentReader-web-openapi#47]
FDSIDList field doesn't contain property ICAO, it should be ICAOCode. Also minLength and maxlength should be 3 instead of 4.

Current situation:
```
ICAO:
  type: string
  minLength: 4
  maxLength: 4
  description: "ICAO code of the issuing country"
```

E.g. FDSIDList object returned from server:

```
{
  "Count": 2,
  "ICAOCode": "HRV",
  "List": [
    14800,
    12510
  ],
  "dCountryName": "Croatia",
  "dFormat": 2,
  "dMRZ": true,
  "dType": 11,
  "dYear": "2009"
}
```
